def Terminal():
  TestedApps.iTools.Run()
  Aliases.iTools.FrmMain.BtnNewClone.Click()
  Aliases.iTools.DlgTemplateFile.TabControl.ClickTab("EPC3000")
  Aliases.iTools.DlgTemplateFile.TabControl.LbxTemplate.ClickItem("EPC3004 V5.20 default")
  Aliases.iTools.DlgTemplateFile.OKBtn.ClickButton()
  Aliases.iTools.WaitChild('VCLObject("DlgServerCommand")',60000)
  Aliases.iTools.FrmMain.WaitChild('VCLObject("BtnTerminalWiring")', 60000)
  Aliases.iTools.FrmMain.BtnTerminalWiring.Click()
  Aliases.iTools.FrmMain.MDIClient.FrmTerminal.Maximize()
  Aliases.iTools.FrmMain.BtnAccessLevel.Click()
  ImageRepository.ImageSet10.Item11.Click()
  Aliases.iTools.FrmMain.MDIClient.FrmTerminal.pnlClient.RearTerminal.ThePageControl.tabDiagram.TPanel.pnlEdit.lblModule.Click()
  Aliases.iTools.Window("ComboLBox", "", 1)
  Aliases.iTools.FrmMain.MDIClient.FrmTerminal.pnlClient.RearTerminal.ThePageControl.tabDiagram.TPanel.pnlEdit.cmbModType.ClickItem("LogicIO (1)")
  Regions.RearTerminal4.Check(Regions.CreateRegionInfo(Aliases.iTools.FrmMain.MDIClient.FrmTerminal.pnlClient.RearTerminal.ThePageControl.tabDiagram.TPanel.RearTerminal, 394, 7, 96, 61, False))
  ImageRepository.ImageSet11.Item12.Click()
  Aliases.iTools.FrmMain.MDIClient.FrmTerminal.pnlClient.RearTerminal.ThePageControl.tabDiagram.TPanel.pnlEdit.lblModule.Click()
  Aliases.iTools.Window("ComboLBox", "", 1)
  Aliases.iTools.FrmMain.MDIClient.FrmTerminal.pnlClient.RearTerminal.ThePageControl.tabDiagram.TPanel.pnlEdit.cmbModType.ClickItem("Relay (2)")
  Regions.RearTerminal7.Check(Regions.CreateRegionInfo(Aliases.iTools.FrmMain.MDIClient.FrmTerminal.pnlClient.RearTerminal.ThePageControl.tabDiagram.TPanel.RearTerminal, 380, 64, 94, 50, False))
  ImageRepository.ImageSet1.Item13.Click()
  Aliases.iTools.FrmMain.MDIClient.FrmTerminal.pnlClient.RearTerminal.ThePageControl.tabDiagram.TPanel.pnlEdit.lblModule.Click()
  Aliases.iTools.Window("ComboLBox", "", 1)
  Aliases.iTools.FrmMain.MDIClient.FrmTerminal.pnlClient.RearTerminal.ThePageControl.tabDiagram.TPanel.pnlEdit.cmbModType.ClickItem("Ssr (3)")
  Regions.RearTerminal9.Check(Regions.CreateRegionInfo(Aliases.iTools.FrmMain.MDIClient.FrmTerminal.pnlClient.RearTerminal.ThePageControl.tabDiagram.TPanel.RearTerminal, 392, 166, 87, 57, False))
  ImageRepository.ImageSet12.Item1C.Click()
  Aliases.iTools.FrmMain.MDIClient.FrmTerminal.pnlClient.RearTerminal.ThePageControl.tabDiagram.TPanel.pnlEdit.cmbPrimary.ClickItem("Yes (1)") 
  Regions.RearTerminal10.Check(Regions.CreateRegionInfo(Aliases.iTools.FrmMain.MDIClient.FrmTerminal.pnlClient.RearTerminal.ThePageControl.tabDiagram.TPanel.RearTerminal, 695, 168, 87, 56, False))
  Aliases.iTools.FrmMain.VCLObject("BtnRemoveFromNetwork").Click()
  Aliases.iTools.TMessageForm2.No.ClickButton()
  Aliases.iTools.FrmMain.Close()